timeout: 1
default_entry: 1
serial: yes

/srvros
    protocol: limine
    path: boot():/boot/srvros.elf
    cmdline: srvros.log=quiet srvros.a1466.capture=1
    module_path: boot():/boot/initramfs.tar
    module_string: initramfs

/srvrosnocapture
    protocol: limine
    path: boot():/boot/srvros.elf
    cmdline: srvros.log=quiet
    module_path: boot():/boot/initramfs.tar
    module_string: initramfs

/srvrosdebug
    protocol: limine
    path: boot():/boot/srvros.elf
    cmdline: srvros.log=debug
    module_path: boot():/boot/initramfs.tar
    module_string: initramfs
